galaxy_info:
  author: Guadaltech
  description: BLK (Bind9 + LDAP + Kerberos)
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags: ['kerberos', 'ldap', 'samba', 'sssd', 'domain', 'ubuntu']
dependencies: []
