---
main_setup: true
bind9_setup: true
ldap_setup: true
kerberos_setup: true
sssd_setup: true

main_uninstall: false
bind9_uninstall: false
ldap_uninstall: false
kerberos_uninstall: false
# Do not use
sssd_uninstall: false

domain: "linux.gstwdt.local"

openldap_linux: '{{ domain.split(".")[0] | lower }}'
openldap_org: '{{ domain.split(".")[1] | lower }}'
openldap_tld: '{{ domain.split(".")[2] | lower }}'

openldap_base: 'dc={{ openldap_linux }},dc={{ openldap_org }},dc={{ openldap_tld }}'
sudoers: "SUDOers"
# In virtualbox: 0 is internal, 1 private and 2 public IP
# For more information see the Vagrantfile
num_interface: 1