---
openldap_admin_user: 'admin'
openldap_admin_password: 'adminpass'
read_only_user: 'queryuser'
password_read_only_user: 'queryuserpass'

# Internal
openldap_bind_user: '{{ openldap_admin_user }}'
openldap_bind_id: 'cn={{ openldap_bind_user }},{{ openldap_base }}'