---
openldap_packages:
  - slapd
  - ldap-utils
  - nslcd
  - libnss-ldapd
  - sudo-ldap
openldap_organizationalunits:  #defines OU's to populate
  - name: Workers
    ou: Workers
    description: Organizational Unit Workers
  - name: "{{ sudoers }}"
    ou: "{{ sudoers }}"
    description: Organizational Unit SUDOERS
  - name: Hostnames
    ou: Hostnames
    description: Organizational Unit Hostnames
openldap_populate: true  #defines if openldap DB should be populated with openldap_organizationalunits, openldap_posixgroups and openldap_users
openldap_cn_sudoers:
  - name: sudobase
    ou: "{{ sudoers }}"
    sudoUser: test
    sudoOrder: 0
openldap_command_sudoers:
  - /usr/bin/apt
  - /usr/bin/apt-*
  - /usr/bin/pip
  - /usr/bin/systemctl
  - /bin/systemctl
  - /usr/sbin/service
  - /usr/bin/crontab
  - /usr/sbin/dhclient

pri_domain_name: '{{ domain }}'
end_sssd: false